Run migration
Added param to drop_table to avoid following error:

Caused by:
ArgumentError: wrong number of arguments (given 2, expected 1) (ArgumentError)
/usr/local/bundle/gems/activerecord-8.0.1/lib/active_record/migration.rb:580:in `create_table'
/usr/local/bundle/gems/activerecord-8.0.1/lib/active_record/migration/command_recorder.rb:150:in `block in replay'
/usr/local/bundle/gems/activerecord-8.0.1/lib/active_record/migration/command_recorder.rb:149:in `each'
/usr/local/bundle/gems/activerecord-8.0.1/lib/active_record/migration/command_recorder.rb:149:in `replay'
/usr/local/bundle/gems/activerecord-8.0.1/lib/active_record/migration.rb:864:in `revert'

Seems to be an issue with Rails 8.0.1 reversing drop_table with no
params, since it works with default params there instead.